<?php
    date_default_timezone_set('America/Chicago');
    session_start();
    include('include/connect.php');
    include('include/db_query.php');
    include('include/helper_functions.php');
    include('include/product.php');
    include('include/common_components.php');
    ?>